### ISSUE TITLE
Info-like keybindings

### ISSUE THREAD

**Issue by egh** [astoff/devdocs.el#2]
Thanks for the package. I'm just getting started but it looks great!

A few `Info` mode like keybindings would be helpful. For instance:
- `i` -> `devdocs-lookup`
- `s` -> `devdocs-search`
- `n` -> `devdocs-go-forward`
- `p` -> `devdocs-go-back`

**Comment by astoff** [comment]
I've pushed some changes I had locally, including keybindings like these. I was debating a bit what the right binding for `devdocs-lookup` is: `i`, `g`, `m`, ...? Maybe the first two?

Note also that `n` and `p` navigate in the order of the devdocs index, which, confusingly, is not necessarily the order in the document.

**Comment by egh** [comment]
Tank you!

I'm new to it all, but `devdocs-lookup` seemed most like an index to me.

**Comment by astoff** [comment]
You're right, I've changed that keybinding to `i`.
