### ISSUE TITLE
Storing links to devdocs

### ISSUE THREAD

**Issue by j-minster** [astoff/devdocs.el#23]
Hi. Thank you for this package. I'd like to ask if there's any way to store links to devdocs buffers for later use? I'd like to use 'org-store-links' to save a link to something I'm reading in devdocs and come back to it later. 

Thanks!

**Comment by astoff** [comment]
There is the `devdocs-copy-url` command (`w` on devdocs buffer) to copy a link to the entry. One can make `browse-url` handle these links in a special way by customizing `browse-url-handlers`. If we find a sensible configuration that makes sense for most users, we can add it to the package.

I'm not famimilar with org-store-links, but, again, please let me know if you find a suitable configuration.

**Comment by astoff** [comment]
@j-minster Did you get a chance to test this, and does it work?

**Comment by astoff** [comment]
I'll close this now, but feel free to comment is anything else comes up.
