### ISSUE TITLE
Incorrect treatment of the default symbol

### ISSUE THREAD

**Issue by vspinu** [astoff/devdocs.el#24]
Currently `devdocs-lookup` uses symbol at point as a default entry. This means that

  1. When the current symbol is not part of thecandidates it is still placed as a default in the completion list. Selecting it results in error. 
  2. The list is not narrowed down to the current input

![image](https://user-images.githubusercontent.com/1363467/207727117-26a18bc7-8671-4f81-bfeb-e223c1cf38c3.png)

I think what most users expect is to have the list narrowed to the symbol-at-point and not to include an invalid match as a default:

![image](https://user-images.githubusercontent.com/1363467/207727975-241f29dd-8624-48cc-81e6-f139935cb5af.png)

**Comment by astoff** [comment]
Let's discuss in the related pull request you just opened.
