### ISSUE TITLE
Docs not installing

### ISSUE THREAD

**Issue by th3r00t** [astoff/devdocs.el#27]
documents appear to download after about 8 sec's connecting to the host, however the directory is not populated, and I can not lookup via M-x devdocs-lookup.

* Installation Block
#+begin_src emacs-lisp
    (use-package devdocs :ensure t
          :config
          (global-set-key (kbd "C-h C-l") '("Dev Docs"))
          (global-set-key (kbd "C-h C-l i") #'("Install Docs" . devdocs-install))
          (global-set-key (kbd "C-h C-l d") #'("Delete Docs" . devdocs-delete))
          (global-set-key (kbd "C-h C-l u") #'("Update Docs" . devdocs-update-all))
          (global-set-key (kbd "C-h C-l l") #'("Lookup Docs" . devdocs-lookup))
          (global-set-key (kbd "C-h C-l p") #'("Peruse Docs" . devdocs-peruse))
      )
#+end_src

* Check Configuration
M-x customize-group

Devdocs Data Dir: Directory: /home/th3r00t/.emacs.d/devdocs
    State : STANDARD.
   Directory to save documentation files.

* Install some docs.
M-x devdocs-install rust
M-x devdocs-install python~3.11

* List the directory.
ls -la ~/.emacs.d/devdocs
returns empty.

drwxr-xr-x    - th3r00t 23 Feb 00:34 ~/.emacs.d/devdocs

Permissions appear to be alright.

**Comment by astoff** [comment]
Everything seems fine for me, can you reproduce this in `emacs -Q`?

**Comment by astoff** [comment]
I'll close this since there has been no response in a while, feel free to comment if you have more details.
