### ISSUE TITLE
[Question] `devdocs-goto-target` seems like `(goto-char 2)`?

### ISSUE THREAD

**Issue by condy0919** [astoff/devdocs.el#4]
The docstring says it will go to the original position. What's the original position meaning?

**Comment by astoff** [comment]
When you select an entry in `devdocs-lookup`, you are supposed to be taken to the location of the entry, not to character 2. That's what that command does.

For which entries of which document do you observe this?

**Comment by condy0919** [comment]
I'm adding evil integration https://github.com/emacs-evil/evil-collection/commit/86b02f84a8df0ddd6216cb85d49bedd6ee2ab747

I'm curious about that so.

**Comment by astoff** [comment]
But do you still think there's a bug with `.`?

FYI, I'm not so happy with `devdocs-next/previous-entry`, I may replace these commands with `devdocs-next/previous-page` at some point.

**Comment by condy0919** [comment]
> But do you still think there's a bug with `.`?

Maybe a video is more expressive than text.

https://user-images.githubusercontent.com/4024656/121246315-a1044b80-c8d3-11eb-8c2c-31282696e5a3.mp4

> FYI, I'm not so happy with `devdocs-next/previous-entry`, I may replace these commands with `devdocs-next/previous-page` at some point.

Thanks, I will keep evil-collection update with it.

**Comment by astoff** [comment]
Okay, I'll check why one lands at the second character rather than the beginning of the line.  Otherwise the command is doing what it should. In these examples, you choose entries located at the top of some page, but this is not always the case.

**Comment by KSSysLab** [comment]
Is it true that there is only one entry in most pages?

**Comment by astoff** [comment]
No, that's not what I observe. Some documents (e.g., Lua) have one single page.

**Comment by KSSysLab** [comment]
Finally I realize the usage of `devdocs-goto-target`.

Would you mind to mention this in the README? I think people will have the same confusion.

**Comment by astoff** [comment]
I'll expand the Readme eventually.
