### ISSUE TITLE
[Feature Request] generate link to https://devdocs.io

### ISSUE THREAD

**Issue by condy0919** [astoff/devdocs.el#5]
So that we can share the link to someone else.

**Comment by astoff** [comment]
Okay, I've added this under to the expected `w` key. Let me know if you find any edge cases.

**Comment by condy0919** [comment]
Thanks, evil-collection is updated https://github.com/emacs-evil/evil-collection/commit/bc5a02ed8572e7d40d04a78f17abc08061dfc37e
